# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dialtone
description: The design system and resources for Dialpad.
baseurl:  # the subpath of your site, e.g. /blog
url: http://dialpad.design # the base hostname & protocol for your site
permalink: pretty

# Build settings
markdown: kramdown
plugins_dir: plugins
lib: assets
img: assets/images
ico: assets/images/favicons
svg: assets/images/icons
scss: assets/scss
css: assets/css
js: assets/js

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: ["README.md", "package.json", "gulpfile.js", "Gruntfile.coffee", "node_modules", "docs-*.html", ".asset-cache", ".jekyll-metadata"]
