name: Lint PR

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
    branches:
      - staging

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # we need + 1 commit
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: '8'

      - name: Use the node_modules cache if available [pnpm]
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ steps.versions.outputs.node_version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ steps.versions.outputs.node_version }}-    

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint pull request commit message when it has a single commit
        if: ${{ github.event.pull_request.commits == '1' }}
        run: |
          echo "Since your PR has a single commit, this commit should adhere to the commit message convention."
          echo "correct format: <type>(<scope>): <subject>"
          echo "example: feat: add dialbot icon"
          echo "Please amend your commit message (git commit --amend) if commitlint reports an error and push using: git push --force-with-lease"
          git show -s --format=%B HEAD^2 | npx commitlint --verbose

      - name: Lint pull request title
        run: |
          echo "The PR's title should adhere to the commit message convention."
          echo "correct format: <type>(<scope>): <subject>"
          echo "example: feat: add dialbot icon"
          npx commitlint --verbose << EOF
          ${{ github.event.pull_request.title }}
          EOF
