name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - production
      - alpha
      - beta
      - next
      - legacy

env:
  HUSKY: 0

jobs:
  release:
    concurrency: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: parse branch from ref
        id: branch
        run: echo ::set-output name=BRANCH::${GITHUB_REF/refs\/heads\//}

      # Will prevent the rest of the steps from running on fail
      - name: Check if user is a dialpad member
        uses: octokit/request-action@v2.1.0
        with:
          route: GET /orgs/dialpad/members/${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.DIALTONE_CI_TOKEN }}

      - name: Check out branch
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: '8'

      - name: Use the node_modules cache if available [pnpm]
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ steps.versions.outputs.node_version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ steps.versions.outputs.node_version }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set npm token
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.DIALTONE_NPM_TOKEN }}

      # note that npm run build is executed before publishing via prepublishOnly
      - name: Deploy production
        if: ${{ github.ref == 'refs/heads/production' }}
        run: npx nx run dialtone-icons@2:release
